Repository hashmaster3k/viewing_party, pull requests merged in 2020-10, with the labels that each got.

#19 Welcome page set up
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/welcome_controller.rb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/welcome/index_spec.rb
Labels: chore, enhancement

#21 User registration
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/user/base_controller.rb
  app/controllers/user/dashboard_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/user/dashboard/index.html.erb
  app/views/users/new.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  db/migrate/20201006203135_create_users.rb
  db/schema.rb
  spec/features/sessions/create_spec.rb
  spec/features/users/new_spec.rb
  spec/features/welcome/index_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: Core, enhancement

#22 Dashboard set up
  app/controllers/sessions_controller.rb
  app/helpers/sessions_helper.rb
  app/models/user.rb
  app/views/user/dashboard/index.html.erb
  spec/features/user/dashboard/index_spec.rb
  spec/models/user_spec.rb
Labels: Core, enhancement, paired commit

#23 Change route for dashboard to fit user story
  app/controllers/users_controller.rb
  app/helpers/sessions_helper.rb
  config/routes.rb
  spec/features/sessions/create_spec.rb
  spec/features/user/dashboard/index_spec.rb
  spec/features/users/new_spec.rb
Labels: refactor

#24 Friends section
  app/models/friend.rb
  app/models/user.rb
  db/migrate/20201007185255_create_friends.rb
  db/schema.rb
  spec/models/friend_spec.rb
  spec/models/user_spec.rb
Labels: Core, paired commit, refactor

#25 Friends Functionality
  app/controllers/friends_controller.rb
  app/views/user/dashboard/_friends.html.erb
  app/views/user/dashboard/index.html.erb
  config/routes.rb
  db/seeds.rb
  spec/features/user/dashboard/index_spec.rb
Labels: ActiveRecord, Core, paired commit

#26 Discover movies
  app/controllers/discover_controller.rb
  app/models/user.rb
  app/views/discover/index.html.erb
  app/views/user/dashboard/index.html.erb
  config/routes.rb
  spec/features/discover/index_spec.rb
Labels: Core, enhancement, refactor

#27 Discover page
  app/controllers/movies_controller.rb
  app/views/discover/index.html.erb
  app/views/movies/index.html.erb
  config/routes.rb
  spec/features/discover/index_spec.rb
Labels: Core

#28 Movie general search title as link
  .gitignore
  app/controllers/movies_controller.rb
  app/views/_search_form.html.erb
  app/views/discover/index.html.erb
  app/views/movies/index.html.erb
  spec/features/discover/index_spec.rb
  spec/features/movies/index_spec.rb
  spec/features/movies/show_spec.rb
Labels: API consumption, Core, enhancement

#29 Movie details
  .travis.yml
  app/assets/stylesheets/application.css
  app/controllers/movies_controller.rb
  app/views/movies/index.html.erb
  app/views/movies/show.html.erb
  config/routes.rb
  spec/features/movies/index_spec.rb
  spec/features/movies/show_spec.rb
  spec/spec_helper.rb
Labels: API consumption, Core

#32 Parties resources
  app/controllers/parties_controller.rb
  app/controllers/user/dashboard_controller.rb
  app/models/party.rb
  app/models/user.rb
  app/models/user_party.rb
  app/views/parties/new.html.erb
  app/views/user/dashboard/index.html.erb
  db/migrate/20201012214018_create_parties.rb
  db/migrate/20201012215816_create_user_parties.rb
  db/schema.rb
  spec/features/parties/new_spec.rb
  spec/features/user/dashboard/index_spec.rb
  spec/models/party_spec.rb
  spec/models/user_parties_spec.rb
  spec/models/user_spec.rb
Labels: ActiveRecord, Core, enhancement, paired commit

#31 Update readme
  README.md
Labels: documentation

#38 Dashboard styling
  app/assets/stylesheets/viewing_parties.css
  app/views/layouts/application.html.erb
  app/views/user/dashboard/index.html.erb
  spec/features/user/dashboard/index_spec.rb
Labels: enhancement, paired commit, refactor

#41 Additional testing
  app/controllers/parties_controller.rb
  app/poros/movie_detail.rb
  app/views/users/new.html.erb
  app/views/welcome/index.html.erb
  spec/facades/movie_facade_spec.rb
  spec/features/parties/new_spec.rb
  spec/poros/movie_details_spec.rb
  spec/poros/movie_spec.rb
  spec/rails_helper.rb
  spec/services/movie_service_spec.rb
Labels: enhancement, refactor

#40 Refactor routes
  app/helpers/sessions_helper.rb
  app/views/user/dashboard/index.html.erb
  app/views/users/new.html.erb
  app/views/welcome/index.html.erb
  config/routes.rb
  spec/features/discover/index_spec.rb
  spec/features/movies/index_spec.rb
  spec/features/sessions/create_spec.rb
  spec/features/users/new_spec.rb
  spec/features/welcome/index_spec.rb
Labels: enhancement, paired commit, refactor

#42 Add badges to readme
  README.md
Labels: documentation, enhancement

#43 Exploration
  app/assets/stylesheets/application.css
  app/controllers/discover_controller.rb
  app/controllers/sessions_controller.rb
  app/facades/movie_facade.rb
  app/poros/movie.rb
  app/poros/movie_detail.rb
  app/services/movie_service.rb
  app/views/discover/index.html.erb
  app/views/layouts/application.html.erb
  app/views/movies/show.html.erb
  config/routes.rb
  spec/features/discover/index_spec.rb
  spec/features/movies/index_spec.rb
  spec/features/movies/show_spec.rb
  spec/features/parties/new_spec.rb
  spec/fixtures/vcr_cassettes/Movie_Search_Phoenix.yml
  spec/fixtures/vcr_cassettes/Movie_details.yml
  spec/fixtures/vcr_cassettes/Top_rated_movies.yml
  spec/fixtures/vcr_cassettes/upcoming_movies.yml
  spec/poros/movie_details_spec.rb
Labels: API consumption, enhancement, paired commit

#44 Fix all rubocop errors
  app/controllers/movies_controller.rb
  app/controllers/sessions_controller.rb
  app/facades/movie_facade.rb
  app/models/party.rb
  app/models/user.rb
  app/services/movie_service.rb
  spec/fixtures/vcr_cassettes/Movie_Search_Phoenix.yml
  spec/fixtures/vcr_cassettes/Movie_details.yml
  spec/fixtures/vcr_cassettes/Top_rated_movies.yml
  spec/fixtures/vcr_cassettes/upcoming_movies.yml
Labels: refactor
